/*
 * Connection Rest API 1.0
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using connection_restapi_client_poc.Model;
using connection_restapi_client_poc.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace connection_restapi_client_poc.Test.Model
{
    /// <summary>
    ///  Class for testing BasePlateShearCheckResDataIdeaStatiCaConnectionChecks
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class BasePlateShearCheckResDataIdeaStatiCaConnectionChecksTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for BasePlateShearCheckResDataIdeaStatiCaConnectionChecks
        //private BasePlateShearCheckResDataIdeaStatiCaConnectionChecks instance;

        public BasePlateShearCheckResDataIdeaStatiCaConnectionChecksTests()
        {
            // TODO uncomment below to create an instance of BasePlateShearCheckResDataIdeaStatiCaConnectionChecks
            //instance = new BasePlateShearCheckResDataIdeaStatiCaConnectionChecks();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of BasePlateShearCheckResDataIdeaStatiCaConnectionChecks
        /// </summary>
        [Fact]
        public void BasePlateShearCheckResDataIdeaStatiCaConnectionChecksInstanceTest()
        {
            // TODO uncomment below to test "IsType" BasePlateShearCheckResDataIdeaStatiCaConnectionChecks
            //Assert.IsType<BasePlateShearCheckResDataIdeaStatiCaConnectionChecks>(instance);
        }

        /// <summary>
        /// Test the property 'Vrdf'
        /// </summary>
        [Fact]
        public void VrdfTest()
        {
            // TODO unit test for the property 'Vrdf'
        }

        /// <summary>
        /// Test the property 'Vrdx'
        /// </summary>
        [Fact]
        public void VrdxTest()
        {
            // TODO unit test for the property 'Vrdx'
        }

        /// <summary>
        /// Test the property 'Vrdy'
        /// </summary>
        [Fact]
        public void VrdyTest()
        {
            // TODO unit test for the property 'Vrdy'
        }

        /// <summary>
        /// Test the property 'Vx'
        /// </summary>
        [Fact]
        public void VxTest()
        {
            // TODO unit test for the property 'Vx'
        }

        /// <summary>
        /// Test the property 'Vy'
        /// </summary>
        [Fact]
        public void VyTest()
        {
            // TODO unit test for the property 'Vy'
        }

        /// <summary>
        /// Test the property 'V'
        /// </summary>
        [Fact]
        public void VTest()
        {
            // TODO unit test for the property 'V'
        }

        /// <summary>
        /// Test the property 'Vr'
        /// </summary>
        [Fact]
        public void VrTest()
        {
            // TODO unit test for the property 'Vr'
        }

        /// <summary>
        /// Test the property 'Pbr'
        /// </summary>
        [Fact]
        public void PbrTest()
        {
            // TODO unit test for the property 'Pbr'
        }

        /// <summary>
        /// Test the property 'Vcb'
        /// </summary>
        [Fact]
        public void VcbTest()
        {
            // TODO unit test for the property 'Vcb'
        }

        /// <summary>
        /// Test the property 'FrictionCoefficient'
        /// </summary>
        [Fact]
        public void FrictionCoefficientTest()
        {
            // TODO unit test for the property 'FrictionCoefficient'
        }

        /// <summary>
        /// Test the property 'ShearIronCss'
        /// </summary>
        [Fact]
        public void ShearIronCssTest()
        {
            // TODO unit test for the property 'ShearIronCss'
        }

        /// <summary>
        /// Test the property 'ShearIronApplied'
        /// </summary>
        [Fact]
        public void ShearIronAppliedTest()
        {
            // TODO unit test for the property 'ShearIronApplied'
        }

        /// <summary>
        /// Test the property 'UnityCheck'
        /// </summary>
        [Fact]
        public void UnityCheckTest()
        {
            // TODO unit test for the property 'UnityCheck'
        }

        /// <summary>
        /// Test the property 'Avx'
        /// </summary>
        [Fact]
        public void AvxTest()
        {
            // TODO unit test for the property 'Avx'
        }

        /// <summary>
        /// Test the property 'Avy'
        /// </summary>
        [Fact]
        public void AvyTest()
        {
            // TODO unit test for the property 'Avy'
        }

        /// <summary>
        /// Test the property 'Fy'
        /// </summary>
        [Fact]
        public void FyTest()
        {
            // TODO unit test for the property 'Fy'
        }

        /// <summary>
        /// Test the property 'Nsd'
        /// </summary>
        [Fact]
        public void NsdTest()
        {
            // TODO unit test for the property 'Nsd'
        }

        /// <summary>
        /// Test the property 'ShearForceTransfer'
        /// </summary>
        [Fact]
        public void ShearForceTransferTest()
        {
            // TODO unit test for the property 'ShearForceTransfer'
        }

        /// <summary>
        /// Test the property 'GammaM0'
        /// </summary>
        [Fact]
        public void GammaM0Test()
        {
            // TODO unit test for the property 'GammaM0'
        }

        /// <summary>
        /// Test the property 'Asd'
        /// </summary>
        [Fact]
        public void AsdTest()
        {
            // TODO unit test for the property 'Asd'
        }

        /// <summary>
        /// Test the property 'PhiOmega'
        /// </summary>
        [Fact]
        public void PhiOmegaTest()
        {
            // TODO unit test for the property 'PhiOmega'
        }

        /// <summary>
        /// Test the property 'BearingResistance'
        /// </summary>
        [Fact]
        public void BearingResistanceTest()
        {
            // TODO unit test for the property 'BearingResistance'
        }

        /// <summary>
        /// Test the property 'NumOfTensionedAnchors'
        /// </summary>
        [Fact]
        public void NumOfTensionedAnchorsTest()
        {
            // TODO unit test for the property 'NumOfTensionedAnchors'
        }

        /// <summary>
        /// Test the property 'PhiBr'
        /// </summary>
        [Fact]
        public void PhiBrTest()
        {
            // TODO unit test for the property 'PhiBr'
        }

        /// <summary>
        /// Test the property 'Fc'
        /// </summary>
        [Fact]
        public void FcTest()
        {
            // TODO unit test for the property 'Fc'
        }

        /// <summary>
        /// Test the property 'AlphaV'
        /// </summary>
        [Fact]
        public void AlphaVTest()
        {
            // TODO unit test for the property 'AlphaV'
        }

        /// <summary>
        /// Test the property 'PsiAlphaV'
        /// </summary>
        [Fact]
        public void PsiAlphaVTest()
        {
            // TODO unit test for the property 'PsiAlphaV'
        }

        /// <summary>
        /// Test the property 'AvcConeBreakoutArea'
        /// </summary>
        [Fact]
        public void AvcConeBreakoutAreaTest()
        {
            // TODO unit test for the property 'AvcConeBreakoutArea'
        }

        /// <summary>
        /// Test the property 'UnityCheckConeBreakoutResistance'
        /// </summary>
        [Fact]
        public void UnityCheckConeBreakoutResistanceTest()
        {
            // TODO unit test for the property 'UnityCheckConeBreakoutResistance'
        }

        /// <summary>
        /// Test the property 'UnityCheckBearingCapacity'
        /// </summary>
        [Fact]
        public void UnityCheckBearingCapacityTest()
        {
            // TODO unit test for the property 'UnityCheckBearingCapacity'
        }

        /// <summary>
        /// Test the property 'PhiC'
        /// </summary>
        [Fact]
        public void PhiCTest()
        {
            // TODO unit test for the property 'PhiC'
        }

        /// <summary>
        /// Test the property 'OmegaC'
        /// </summary>
        [Fact]
        public void OmegaCTest()
        {
            // TODO unit test for the property 'OmegaC'
        }

        /// <summary>
        /// Test the property 'PhiS'
        /// </summary>
        [Fact]
        public void PhiSTest()
        {
            // TODO unit test for the property 'PhiS'
        }

        /// <summary>
        /// Test the property 'ShearLugForce'
        /// </summary>
        [Fact]
        public void ShearLugForceTest()
        {
            // TODO unit test for the property 'ShearLugForce'
        }

        /// <summary>
        /// Test the property 'ShearLugForceComponent'
        /// </summary>
        [Fact]
        public void ShearLugForceComponentTest()
        {
            // TODO unit test for the property 'ShearLugForceComponent'
        }

        /// <summary>
        /// Test the property 'ConeBreakoutCheckType'
        /// </summary>
        [Fact]
        public void ConeBreakoutCheckTypeTest()
        {
            // TODO unit test for the property 'ConeBreakoutCheckType'
        }

        /// <summary>
        /// Test the property 'ShearLugProjectionArea'
        /// </summary>
        [Fact]
        public void ShearLugProjectionAreaTest()
        {
            // TODO unit test for the property 'ShearLugProjectionArea'
        }

        /// <summary>
        /// Test the property 'CompForce'
        /// </summary>
        [Fact]
        public void CompForceTest()
        {
            // TODO unit test for the property 'CompForce'
        }

        /// <summary>
        /// Test the property 'Kc'
        /// </summary>
        [Fact]
        public void KcTest()
        {
            // TODO unit test for the property 'Kc'
        }

        /// <summary>
        /// Test the property 'ConnectorTensileArea'
        /// </summary>
        [Fact]
        public void ConnectorTensileAreaTest()
        {
            // TODO unit test for the property 'ConnectorTensileArea'
        }

        /// <summary>
        /// Test the property 'ConnectorFy'
        /// </summary>
        [Fact]
        public void ConnectorFyTest()
        {
            // TODO unit test for the property 'ConnectorFy'
        }

        /// <summary>
        /// Test the property 'Ny'
        /// </summary>
        [Fact]
        public void NyTest()
        {
            // TODO unit test for the property 'Ny'
        }

        /// <summary>
        /// Test the property 'Pa'
        /// </summary>
        [Fact]
        public void PaTest()
        {
            // TODO unit test for the property 'Pa'
        }

        /// <summary>
        /// Test the property 'A'
        /// </summary>
        [Fact]
        public void ATest()
        {
            // TODO unit test for the property 'A'
        }

        /// <summary>
        /// Test the property 'L'
        /// </summary>
        [Fact]
        public void LTest()
        {
            // TODO unit test for the property 'L'
        }

        /// <summary>
        /// Test the property 'B'
        /// </summary>
        [Fact]
        public void BTest()
        {
            // TODO unit test for the property 'B'
        }

        /// <summary>
        /// Test the property 'GammaC'
        /// </summary>
        [Fact]
        public void GammaCTest()
        {
            // TODO unit test for the property 'GammaC'
        }

        /// <summary>
        /// Test the property 'VFactor'
        /// </summary>
        [Fact]
        public void VFactorTest()
        {
            // TODO unit test for the property 'VFactor'
        }

        /// <summary>
        /// Test the property 'K1Factor'
        /// </summary>
        [Fact]
        public void K1FactorTest()
        {
            // TODO unit test for the property 'K1Factor'
        }

        /// <summary>
        /// Test the property 'SigmaRdmax'
        /// </summary>
        [Fact]
        public void SigmaRdmaxTest()
        {
            // TODO unit test for the property 'SigmaRdmax'
        }

        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }

        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }

        /// <summary>
        /// Test the property 'CheckStatus'
        /// </summary>
        [Fact]
        public void CheckStatusTest()
        {
            // TODO unit test for the property 'CheckStatus'
        }

        /// <summary>
        /// Test the property 'LimitCheckStatus'
        /// </summary>
        [Fact]
        public void LimitCheckStatusTest()
        {
            // TODO unit test for the property 'LimitCheckStatus'
        }

        /// <summary>
        /// Test the property 'LoadCaseId'
        /// </summary>
        [Fact]
        public void LoadCaseIdTest()
        {
            // TODO unit test for the property 'LoadCaseId'
        }

        /// <summary>
        /// Test the property 'LoadCase'
        /// </summary>
        [Fact]
        public void LoadCaseTest()
        {
            // TODO unit test for the property 'LoadCase'
        }

        /// <summary>
        /// Test the property 'MaxUnityCheck'
        /// </summary>
        [Fact]
        public void MaxUnityCheckTest()
        {
            // TODO unit test for the property 'MaxUnityCheck'
        }

        /// <summary>
        /// Test the property 'Form'
        /// </summary>
        [Fact]
        public void FormTest()
        {
            // TODO unit test for the property 'Form'
        }
    }
}
