/*
 * Connection Rest API 1.0
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using connection_restapi_client_poc.Model;
using connection_restapi_client_poc.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace connection_restapi_client_poc.Test.Model
{
    /// <summary>
    ///  Class for testing BoltCheckResDataTimberIdeaStatiCaConnectionChecks
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class BoltCheckResDataTimberIdeaStatiCaConnectionChecksTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for BoltCheckResDataTimberIdeaStatiCaConnectionChecks
        //private BoltCheckResDataTimberIdeaStatiCaConnectionChecks instance;

        public BoltCheckResDataTimberIdeaStatiCaConnectionChecksTests()
        {
            // TODO uncomment below to create an instance of BoltCheckResDataTimberIdeaStatiCaConnectionChecks
            //instance = new BoltCheckResDataTimberIdeaStatiCaConnectionChecks();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of BoltCheckResDataTimberIdeaStatiCaConnectionChecks
        /// </summary>
        [Fact]
        public void BoltCheckResDataTimberIdeaStatiCaConnectionChecksInstanceTest()
        {
            // TODO uncomment below to test "IsType" BoltCheckResDataTimberIdeaStatiCaConnectionChecks
            //Assert.IsType<BoltCheckResDataTimberIdeaStatiCaConnectionChecks>(instance);
        }

        /// <summary>
        /// Test the property 'BoltTensionResistance'
        /// </summary>
        [Fact]
        public void BoltTensionResistanceTest()
        {
            // TODO unit test for the property 'BoltTensionResistance'
        }

        /// <summary>
        /// Test the property 'BoltPunchingResistance'
        /// </summary>
        [Fact]
        public void BoltPunchingResistanceTest()
        {
            // TODO unit test for the property 'BoltPunchingResistance'
        }

        /// <summary>
        /// Test the property 'BoltTensionForce'
        /// </summary>
        [Fact]
        public void BoltTensionForceTest()
        {
            // TODO unit test for the property 'BoltTensionForce'
        }

        /// <summary>
        /// Test the property 'BoltShearResistance'
        /// </summary>
        [Fact]
        public void BoltShearResistanceTest()
        {
            // TODO unit test for the property 'BoltShearResistance'
        }

        /// <summary>
        /// Test the property 'BoltShearResistanceTension'
        /// </summary>
        [Fact]
        public void BoltShearResistanceTensionTest()
        {
            // TODO unit test for the property 'BoltShearResistanceTension'
        }

        /// <summary>
        /// Test the property 'BoltBearingResistance'
        /// </summary>
        [Fact]
        public void BoltBearingResistanceTest()
        {
            // TODO unit test for the property 'BoltBearingResistance'
        }

        /// <summary>
        /// Test the property 'BearingResistanceBolt'
        /// </summary>
        [Fact]
        public void BearingResistanceBoltTest()
        {
            // TODO unit test for the property 'BearingResistanceBolt'
        }

        /// <summary>
        /// Test the property 'BearingResistanceConPart'
        /// </summary>
        [Fact]
        public void BearingResistanceConPartTest()
        {
            // TODO unit test for the property 'BearingResistanceConPart'
        }

        /// <summary>
        /// Test the property 'BoltShearForce'
        /// </summary>
        [Fact]
        public void BoltShearForceTest()
        {
            // TODO unit test for the property 'BoltShearForce'
        }

        /// <summary>
        /// Test the property 'NumberOfShearPlanes'
        /// </summary>
        [Fact]
        public void NumberOfShearPlanesTest()
        {
            // TODO unit test for the property 'NumberOfShearPlanes'
        }

        /// <summary>
        /// Test the property 'BoltShearForces'
        /// </summary>
        [Fact]
        public void BoltShearForcesTest()
        {
            // TODO unit test for the property 'BoltShearForces'
        }

        /// <summary>
        /// Test the property 'UnityCheckTension'
        /// </summary>
        [Fact]
        public void UnityCheckTensionTest()
        {
            // TODO unit test for the property 'UnityCheckTension'
        }

        /// <summary>
        /// Test the property 'UnityCheckTensionRes'
        /// </summary>
        [Fact]
        public void UnityCheckTensionResTest()
        {
            // TODO unit test for the property 'UnityCheckTensionRes'
        }

        /// <summary>
        /// Test the property 'UnityCheckShear'
        /// </summary>
        [Fact]
        public void UnityCheckShearTest()
        {
            // TODO unit test for the property 'UnityCheckShear'
        }

        /// <summary>
        /// Test the property 'BoltAssemblyName'
        /// </summary>
        [Fact]
        public void BoltAssemblyNameTest()
        {
            // TODO unit test for the property 'BoltAssemblyName'
        }

        /// <summary>
        /// Test the property 'BoltTensionForceLoadcase'
        /// </summary>
        [Fact]
        public void BoltTensionForceLoadcaseTest()
        {
            // TODO unit test for the property 'BoltTensionForceLoadcase'
        }

        /// <summary>
        /// Test the property 'BoltShearForceLoadcase'
        /// </summary>
        [Fact]
        public void BoltShearForceLoadcaseTest()
        {
            // TODO unit test for the property 'BoltShearForceLoadcase'
        }

        /// <summary>
        /// Test the property 'BoltInteractionLoadcase'
        /// </summary>
        [Fact]
        public void BoltInteractionLoadcaseTest()
        {
            // TODO unit test for the property 'BoltInteractionLoadcase'
        }

        /// <summary>
        /// Test the property 'BoltTensionForceLoadcaseId'
        /// </summary>
        [Fact]
        public void BoltTensionForceLoadcaseIdTest()
        {
            // TODO unit test for the property 'BoltTensionForceLoadcaseId'
        }

        /// <summary>
        /// Test the property 'BoltShearForceLoadcaseId'
        /// </summary>
        [Fact]
        public void BoltShearForceLoadcaseIdTest()
        {
            // TODO unit test for the property 'BoltShearForceLoadcaseId'
        }

        /// <summary>
        /// Test the property 'BoltInteractionLoadcaseId'
        /// </summary>
        [Fact]
        public void BoltInteractionLoadcaseIdTest()
        {
            // TODO unit test for the property 'BoltInteractionLoadcaseId'
        }

        /// <summary>
        /// Test the property 'ForcesAllLoadCases'
        /// </summary>
        [Fact]
        public void ForcesAllLoadCasesTest()
        {
            // TODO unit test for the property 'ForcesAllLoadCases'
        }

        /// <summary>
        /// Test the property 'ElementAxisY'
        /// </summary>
        [Fact]
        public void ElementAxisYTest()
        {
            // TODO unit test for the property 'ElementAxisY'
        }

        /// <summary>
        /// Test the property 'ElementAxisZ'
        /// </summary>
        [Fact]
        public void ElementAxisZTest()
        {
            // TODO unit test for the property 'ElementAxisZ'
        }

        /// <summary>
        /// Test the property 'UnityCheckBearing'
        /// </summary>
        [Fact]
        public void UnityCheckBearingTest()
        {
            // TODO unit test for the property 'UnityCheckBearing'
        }

        /// <summary>
        /// Test the property 'CodeType'
        /// </summary>
        [Fact]
        public void CodeTypeTest()
        {
            // TODO unit test for the property 'CodeType'
        }

        /// <summary>
        /// Test the property 'ConnectorGripLength'
        /// </summary>
        [Fact]
        public void ConnectorGripLengthTest()
        {
            // TODO unit test for the property 'ConnectorGripLength'
        }

        /// <summary>
        /// Test the property 'FillerPlatesPackTh'
        /// </summary>
        [Fact]
        public void FillerPlatesPackThTest()
        {
            // TODO unit test for the property 'FillerPlatesPackTh'
        }

        /// <summary>
        /// Test the property 'Angle'
        /// </summary>
        [Fact]
        public void AngleTest()
        {
            // TODO unit test for the property 'Angle'
        }

        /// <summary>
        /// Test the property 'Fub'
        /// </summary>
        [Fact]
        public void FubTest()
        {
            // TODO unit test for the property 'Fub'
        }

        /// <summary>
        /// Test the property 'AFtrd'
        /// </summary>
        [Fact]
        public void AFtrdTest()
        {
            // TODO unit test for the property 'AFtrd'
        }

        /// <summary>
        /// Test the property 'AFvrd'
        /// </summary>
        [Fact]
        public void AFvrdTest()
        {
            // TODO unit test for the property 'AFvrd'
        }

        /// <summary>
        /// Test the property 'K2'
        /// </summary>
        [Fact]
        public void K2Test()
        {
            // TODO unit test for the property 'K2'
        }

        /// <summary>
        /// Test the property 'AlfaV'
        /// </summary>
        [Fact]
        public void AlfaVTest()
        {
            // TODO unit test for the property 'AlfaV'
        }

        /// <summary>
        /// Test the property 'TpBprd'
        /// </summary>
        [Fact]
        public void TpBprdTest()
        {
            // TODO unit test for the property 'TpBprd'
        }

        /// <summary>
        /// Test the property 'FuBprd'
        /// </summary>
        [Fact]
        public void FuBprdTest()
        {
            // TODO unit test for the property 'FuBprd'
        }

        /// <summary>
        /// Test the property 'DmBprd'
        /// </summary>
        [Fact]
        public void DmBprdTest()
        {
            // TODO unit test for the property 'DmBprd'
        }

        /// <summary>
        /// Test the property 'GammaM2'
        /// </summary>
        [Fact]
        public void GammaM2Test()
        {
            // TODO unit test for the property 'GammaM2'
        }

        /// <summary>
        /// Test the property 'DFbrd'
        /// </summary>
        [Fact]
        public void DFbrdTest()
        {
            // TODO unit test for the property 'DFbrd'
        }

        /// <summary>
        /// Test the property 'ThFbrd'
        /// </summary>
        [Fact]
        public void ThFbrdTest()
        {
            // TODO unit test for the property 'ThFbrd'
        }

        /// <summary>
        /// Test the property 'K1'
        /// </summary>
        [Fact]
        public void K1Test()
        {
            // TODO unit test for the property 'K1'
        }

        /// <summary>
        /// Test the property 'AlphaB'
        /// </summary>
        [Fact]
        public void AlphaBTest()
        {
            // TODO unit test for the property 'AlphaB'
        }

        /// <summary>
        /// Test the property 'GammaM3'
        /// </summary>
        [Fact]
        public void GammaM3Test()
        {
            // TODO unit test for the property 'GammaM3'
        }

        /// <summary>
        /// Test the property 'MomentResistance'
        /// </summary>
        [Fact]
        public void MomentResistanceTest()
        {
            // TODO unit test for the property 'MomentResistance'
        }

        /// <summary>
        /// Test the property 'UnityCheckBending'
        /// </summary>
        [Fact]
        public void UnityCheckBendingTest()
        {
            // TODO unit test for the property 'UnityCheckBending'
        }

        /// <summary>
        /// Test the property 'BoltMomentForce'
        /// </summary>
        [Fact]
        public void BoltMomentForceTest()
        {
            // TODO unit test for the property 'BoltMomentForce'
        }

        /// <summary>
        /// Test the property 'BearingResistance'
        /// </summary>
        [Fact]
        public void BearingResistanceTest()
        {
            // TODO unit test for the property 'BearingResistance'
        }

        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }

        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }

        /// <summary>
        /// Test the property 'CheckStatus'
        /// </summary>
        [Fact]
        public void CheckStatusTest()
        {
            // TODO unit test for the property 'CheckStatus'
        }

        /// <summary>
        /// Test the property 'LimitCheckStatus'
        /// </summary>
        [Fact]
        public void LimitCheckStatusTest()
        {
            // TODO unit test for the property 'LimitCheckStatus'
        }

        /// <summary>
        /// Test the property 'LoadCaseId'
        /// </summary>
        [Fact]
        public void LoadCaseIdTest()
        {
            // TODO unit test for the property 'LoadCaseId'
        }

        /// <summary>
        /// Test the property 'LoadCase'
        /// </summary>
        [Fact]
        public void LoadCaseTest()
        {
            // TODO unit test for the property 'LoadCase'
        }

        /// <summary>
        /// Test the property 'MaxUnityCheck'
        /// </summary>
        [Fact]
        public void MaxUnityCheckTest()
        {
            // TODO unit test for the property 'MaxUnityCheck'
        }

        /// <summary>
        /// Test the property 'Form'
        /// </summary>
        [Fact]
        public void FormTest()
        {
            // TODO unit test for the property 'Form'
        }
    }
}
