/*
 * Connection Rest API 1.0
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using connection_restapi_client_poc.Model;
using connection_restapi_client_poc.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace connection_restapi_client_poc.Test.Model
{
    /// <summary>
    ///  Class for testing CIGeometry2DIPolyLine2DCIBasicTypes
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class CIGeometry2DIPolyLine2DCIBasicTypesTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for CIGeometry2DIPolyLine2DCIBasicTypes
        //private CIGeometry2DIPolyLine2DCIBasicTypes instance;

        public CIGeometry2DIPolyLine2DCIBasicTypesTests()
        {
            // TODO uncomment below to create an instance of CIGeometry2DIPolyLine2DCIBasicTypes
            //instance = new CIGeometry2DIPolyLine2DCIBasicTypes();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of CIGeometry2DIPolyLine2DCIBasicTypes
        /// </summary>
        [Fact]
        public void CIGeometry2DIPolyLine2DCIBasicTypesInstanceTest()
        {
            // TODO uncomment below to test "IsType" CIGeometry2DIPolyLine2DCIBasicTypes
            //Assert.IsType<CIGeometry2DIPolyLine2DCIBasicTypes>(instance);
        }

        /// <summary>
        /// Test the property 'StartPoint'
        /// </summary>
        [Fact]
        public void StartPointTest()
        {
            // TODO unit test for the property 'StartPoint'
        }

        /// <summary>
        /// Test the property 'IsClosed'
        /// </summary>
        [Fact]
        public void IsClosedTest()
        {
            // TODO unit test for the property 'IsClosed'
        }

        /// <summary>
        /// Test the property 'Segments'
        /// </summary>
        [Fact]
        public void SegmentsTest()
        {
            // TODO unit test for the property 'Segments'
        }

        /// <summary>
        /// Test the property 'Length'
        /// </summary>
        [Fact]
        public void LengthTest()
        {
            // TODO unit test for the property 'Length'
        }

        /// <summary>
        /// Test the property 'Bounds'
        /// </summary>
        [Fact]
        public void BoundsTest()
        {
            // TODO unit test for the property 'Bounds'
        }

        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
    }
}
