/*
 * Connection Rest API 1.0
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using connection_restapi_client_poc.Model;
using connection_restapi_client_poc.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace connection_restapi_client_poc.Test.Model
{
    /// <summary>
    ///  Class for testing CIGeometry2DISegment2DCIBasicTypes
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class CIGeometry2DISegment2DCIBasicTypesTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for CIGeometry2DISegment2DCIBasicTypes
        //private CIGeometry2DISegment2DCIBasicTypes instance;

        public CIGeometry2DISegment2DCIBasicTypesTests()
        {
            // TODO uncomment below to create an instance of CIGeometry2DISegment2DCIBasicTypes
            //instance = new CIGeometry2DISegment2DCIBasicTypes();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of CIGeometry2DISegment2DCIBasicTypes
        /// </summary>
        [Fact]
        public void CIGeometry2DISegment2DCIBasicTypesInstanceTest()
        {
            // TODO uncomment below to test "IsType" CIGeometry2DISegment2DCIBasicTypes
            //Assert.IsType<CIGeometry2DISegment2DCIBasicTypes>(instance);
        }

        /// <summary>
        /// Test the property 'EndPoint'
        /// </summary>
        [Fact]
        public void EndPointTest()
        {
            // TODO unit test for the property 'EndPoint'
        }
    }
}
