/*
 * Connection Rest API 1.0
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using connection_restapi_client_poc.Model;
using connection_restapi_client_poc.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace connection_restapi_client_poc.Test.Model
{
    /// <summary>
    ///  Class for testing ConConnection
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ConConnectionTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ConConnection
        //private ConConnection instance;

        public ConConnectionTests()
        {
            // TODO uncomment below to create an instance of ConConnection
            //instance = new ConConnection();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ConConnection
        /// </summary>
        [Fact]
        public void ConConnectionInstanceTest()
        {
            // TODO uncomment below to test "IsType" ConConnection
            //Assert.IsType<ConConnection>(instance);
        }

        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }

        /// <summary>
        /// Test the property 'Identifier'
        /// </summary>
        [Fact]
        public void IdentifierTest()
        {
            // TODO unit test for the property 'Identifier'
        }

        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }

        /// <summary>
        /// Test the property 'Description'
        /// </summary>
        [Fact]
        public void DescriptionTest()
        {
            // TODO unit test for the property 'Description'
        }

        /// <summary>
        /// Test the property 'AnalysisType'
        /// </summary>
        [Fact]
        public void AnalysisTypeTest()
        {
            // TODO unit test for the property 'AnalysisType'
        }

        /// <summary>
        /// Test the property 'LoadOptions'
        /// </summary>
        [Fact]
        public void LoadOptionsTest()
        {
            // TODO unit test for the property 'LoadOptions'
        }

        /// <summary>
        /// Test the property 'BearingMemberId'
        /// </summary>
        [Fact]
        public void BearingMemberIdTest()
        {
            // TODO unit test for the property 'BearingMemberId'
        }

        /// <summary>
        /// Test the property 'IsCalculated'
        /// </summary>
        [Fact]
        public void IsCalculatedTest()
        {
            // TODO unit test for the property 'IsCalculated'
        }
    }
}
