/*
 * Connection Rest API 1.0
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using connection_restapi_client_poc.Model;
using connection_restapi_client_poc.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace connection_restapi_client_poc.Test.Model
{
    /// <summary>
    ///  Class for testing ConMember
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ConMemberTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ConMember
        //private ConMember instance;

        public ConMemberTests()
        {
            // TODO uncomment below to create an instance of ConMember
            //instance = new ConMember();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ConMember
        /// </summary>
        [Fact]
        public void ConMemberInstanceTest()
        {
            // TODO uncomment below to test "IsType" ConMember
            //Assert.IsType<ConMember>(instance);
        }

        /// <summary>
        /// Test the property 'IsContinuous'
        /// </summary>
        [Fact]
        public void IsContinuousTest()
        {
            // TODO unit test for the property 'IsContinuous'
        }

        /// <summary>
        /// Test the property 'CrossSectionId'
        /// </summary>
        [Fact]
        public void CrossSectionIdTest()
        {
            // TODO unit test for the property 'CrossSectionId'
        }

        /// <summary>
        /// Test the property 'MirrorY'
        /// </summary>
        [Fact]
        public void MirrorYTest()
        {
            // TODO unit test for the property 'MirrorY'
        }

        /// <summary>
        /// Test the property 'MirrorZ'
        /// </summary>
        [Fact]
        public void MirrorZTest()
        {
            // TODO unit test for the property 'MirrorZ'
        }

        /// <summary>
        /// Test the property 'IsBearing'
        /// </summary>
        [Fact]
        public void IsBearingTest()
        {
            // TODO unit test for the property 'IsBearing'
        }

        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }

        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }

        /// <summary>
        /// Test the property 'Active'
        /// </summary>
        [Fact]
        public void ActiveTest()
        {
            // TODO unit test for the property 'Active'
        }
    }
}
