/*
 * Connection Rest API 1.0
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using connection_restapi_client_poc.Model;
using connection_restapi_client_poc.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace connection_restapi_client_poc.Test.Model
{
    /// <summary>
    ///  Class for testing ConnectionCutBeamByBeamDataIdeaRSOpenModel
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ConnectionCutBeamByBeamDataIdeaRSOpenModelTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ConnectionCutBeamByBeamDataIdeaRSOpenModel
        //private ConnectionCutBeamByBeamDataIdeaRSOpenModel instance;

        public ConnectionCutBeamByBeamDataIdeaRSOpenModelTests()
        {
            // TODO uncomment below to create an instance of ConnectionCutBeamByBeamDataIdeaRSOpenModel
            //instance = new ConnectionCutBeamByBeamDataIdeaRSOpenModel();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ConnectionCutBeamByBeamDataIdeaRSOpenModel
        /// </summary>
        [Fact]
        public void ConnectionCutBeamByBeamDataIdeaRSOpenModelInstanceTest()
        {
            // TODO uncomment below to test "IsType" ConnectionCutBeamByBeamDataIdeaRSOpenModel
            //Assert.IsType<ConnectionCutBeamByBeamDataIdeaRSOpenModel>(instance);
        }

        /// <summary>
        /// Test the property 'ModifiedObject'
        /// </summary>
        [Fact]
        public void ModifiedObjectTest()
        {
            // TODO unit test for the property 'ModifiedObject'
        }

        /// <summary>
        /// Test the property 'CuttingObject'
        /// </summary>
        [Fact]
        public void CuttingObjectTest()
        {
            // TODO unit test for the property 'CuttingObject'
        }

        /// <summary>
        /// Test the property 'IsWeld'
        /// </summary>
        [Fact]
        public void IsWeldTest()
        {
            // TODO unit test for the property 'IsWeld'
        }

        /// <summary>
        /// Test the property 'WeldThickness'
        /// </summary>
        [Fact]
        public void WeldThicknessTest()
        {
            // TODO unit test for the property 'WeldThickness'
        }

        /// <summary>
        /// Test the property 'WeldType'
        /// </summary>
        [Fact]
        public void WeldTypeTest()
        {
            // TODO unit test for the property 'WeldType'
        }

        /// <summary>
        /// Test the property 'Offset'
        /// </summary>
        [Fact]
        public void OffsetTest()
        {
            // TODO unit test for the property 'Offset'
        }

        /// <summary>
        /// Test the property 'Method'
        /// </summary>
        [Fact]
        public void MethodTest()
        {
            // TODO unit test for the property 'Method'
        }

        /// <summary>
        /// Test the property 'Orientation'
        /// </summary>
        [Fact]
        public void OrientationTest()
        {
            // TODO unit test for the property 'Orientation'
        }

        /// <summary>
        /// Test the property 'PlaneOnCuttingObject'
        /// </summary>
        [Fact]
        public void PlaneOnCuttingObjectTest()
        {
            // TODO unit test for the property 'PlaneOnCuttingObject'
        }

        /// <summary>
        /// Test the property 'CutPart'
        /// </summary>
        [Fact]
        public void CutPartTest()
        {
            // TODO unit test for the property 'CutPart'
        }
    }
}
