/*
 * Connection Rest API 1.0
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using connection_restapi_client_poc.Model;
using connection_restapi_client_poc.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace connection_restapi_client_poc.Test.Model
{
    /// <summary>
    ///  Class for testing CostEstimationItemBoltIdeaStatiCaConnectionChecks
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class CostEstimationItemBoltIdeaStatiCaConnectionChecksTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for CostEstimationItemBoltIdeaStatiCaConnectionChecks
        //private CostEstimationItemBoltIdeaStatiCaConnectionChecks instance;

        public CostEstimationItemBoltIdeaStatiCaConnectionChecksTests()
        {
            // TODO uncomment below to create an instance of CostEstimationItemBoltIdeaStatiCaConnectionChecks
            //instance = new CostEstimationItemBoltIdeaStatiCaConnectionChecks();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of CostEstimationItemBoltIdeaStatiCaConnectionChecks
        /// </summary>
        [Fact]
        public void CostEstimationItemBoltIdeaStatiCaConnectionChecksInstanceTest()
        {
            // TODO uncomment below to test "IsType" CostEstimationItemBoltIdeaStatiCaConnectionChecks
            //Assert.IsType<CostEstimationItemBoltIdeaStatiCaConnectionChecks>(instance);
        }

        /// <summary>
        /// Test the property 'UniqueId'
        /// </summary>
        [Fact]
        public void UniqueIdTest()
        {
            // TODO unit test for the property 'UniqueId'
        }

        /// <summary>
        /// Test the property 'UnitCost'
        /// </summary>
        [Fact]
        public void UnitCostTest()
        {
            // TODO unit test for the property 'UnitCost'
        }

        /// <summary>
        /// Test the property 'Cost'
        /// </summary>
        [Fact]
        public void CostTest()
        {
            // TODO unit test for the property 'Cost'
        }

        /// <summary>
        /// Test the property 'TotalWeight'
        /// </summary>
        [Fact]
        public void TotalWeightTest()
        {
            // TODO unit test for the property 'TotalWeight'
        }

        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }

        /// <summary>
        /// Test the property 'Grade'
        /// </summary>
        [Fact]
        public void GradeTest()
        {
            // TODO unit test for the property 'Grade'
        }
    }
}
