/*
 * Connection Rest API 1.0
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using connection_restapi_client_poc.Model;
using connection_restapi_client_poc.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace connection_restapi_client_poc.Test.Model
{
    /// <summary>
    ///  Class for testing CutData
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class CutDataTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for CutData
        //private CutData instance;

        public CutDataTests()
        {
            // TODO uncomment below to create an instance of CutData
            //instance = new CutData();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of CutData
        /// </summary>
        [Fact]
        public void CutDataInstanceTest()
        {
            // TODO uncomment below to test "IsType" CutData
            //Assert.IsType<CutData>(instance);
        }

        /// <summary>
        /// Test the property 'PlanePoint'
        /// </summary>
        [Fact]
        public void PlanePointTest()
        {
            // TODO unit test for the property 'PlanePoint'
        }

        /// <summary>
        /// Test the property 'NormalVector'
        /// </summary>
        [Fact]
        public void NormalVectorTest()
        {
            // TODO unit test for the property 'NormalVector'
        }

        /// <summary>
        /// Test the property 'Direction'
        /// </summary>
        [Fact]
        public void DirectionTest()
        {
            // TODO unit test for the property 'Direction'
        }

        /// <summary>
        /// Test the property 'Offset'
        /// </summary>
        [Fact]
        public void OffsetTest()
        {
            // TODO unit test for the property 'Offset'
        }
    }
}
