/*
 * Connection Rest API 1.0
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using connection_restapi_client_poc.Model;
using connection_restapi_client_poc.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace connection_restapi_client_poc.Test.Model
{
    /// <summary>
    ///  Class for testing DataDetailingDetailingChecksWeldCIBasicTypes
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class DataDetailingDetailingChecksWeldCIBasicTypesTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for DataDetailingDetailingChecksWeldCIBasicTypes
        //private DataDetailingDetailingChecksWeldCIBasicTypes instance;

        public DataDetailingDetailingChecksWeldCIBasicTypesTests()
        {
            // TODO uncomment below to create an instance of DataDetailingDetailingChecksWeldCIBasicTypes
            //instance = new DataDetailingDetailingChecksWeldCIBasicTypes();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of DataDetailingDetailingChecksWeldCIBasicTypes
        /// </summary>
        [Fact]
        public void DataDetailingDetailingChecksWeldCIBasicTypesInstanceTest()
        {
            // TODO uncomment below to test "IsType" DataDetailingDetailingChecksWeldCIBasicTypes
            //Assert.IsType<DataDetailingDetailingChecksWeldCIBasicTypes>(instance);
        }

        /// <summary>
        /// Test the property 'UseFilletWeldLegSize'
        /// </summary>
        [Fact]
        public void UseFilletWeldLegSizeTest()
        {
            // TODO unit test for the property 'UseFilletWeldLegSize'
        }

        /// <summary>
        /// Test the property 'IsPJPWeld'
        /// </summary>
        [Fact]
        public void IsPJPWeldTest()
        {
            // TODO unit test for the property 'IsPJPWeld'
        }

        /// <summary>
        /// Test the property 'Results'
        /// </summary>
        [Fact]
        public void ResultsTest()
        {
            // TODO unit test for the property 'Results'
        }
    }
}
