/*
 * Connection Rest API 1.0
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using connection_restapi_client_poc.Model;
using connection_restapi_client_poc.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace connection_restapi_client_poc.Test.Model
{
    /// <summary>
    ///  Class for testing FatigueCheckResDataIdeaStatiCaConnectionChecks
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class FatigueCheckResDataIdeaStatiCaConnectionChecksTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for FatigueCheckResDataIdeaStatiCaConnectionChecks
        //private FatigueCheckResDataIdeaStatiCaConnectionChecks instance;

        public FatigueCheckResDataIdeaStatiCaConnectionChecksTests()
        {
            // TODO uncomment below to create an instance of FatigueCheckResDataIdeaStatiCaConnectionChecks
            //instance = new FatigueCheckResDataIdeaStatiCaConnectionChecks();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of FatigueCheckResDataIdeaStatiCaConnectionChecks
        /// </summary>
        [Fact]
        public void FatigueCheckResDataIdeaStatiCaConnectionChecksInstanceTest()
        {
            // TODO uncomment below to test "IsType" FatigueCheckResDataIdeaStatiCaConnectionChecks
            //Assert.IsType<FatigueCheckResDataIdeaStatiCaConnectionChecks>(instance);
        }

        /// <summary>
        /// Test the property 'StressDiagram'
        /// </summary>
        [Fact]
        public void StressDiagramTest()
        {
            // TODO unit test for the property 'StressDiagram'
        }

        /// <summary>
        /// Test the property 'StressDiagramTau'
        /// </summary>
        [Fact]
        public void StressDiagramTauTest()
        {
            // TODO unit test for the property 'StressDiagramTau'
        }

        /// <summary>
        /// Test the property 'PlateUID'
        /// </summary>
        [Fact]
        public void PlateUIDTest()
        {
            // TODO unit test for the property 'PlateUID'
        }

        /// <summary>
        /// Test the property 'JoinedItemName'
        /// </summary>
        [Fact]
        public void JoinedItemNameTest()
        {
            // TODO unit test for the property 'JoinedItemName'
        }

        /// <summary>
        /// Test the property 'WeldType2'
        /// </summary>
        [Fact]
        public void WeldType2Test()
        {
            // TODO unit test for the property 'WeldType2'
        }

        /// <summary>
        /// Test the property 'DesignedThickness'
        /// </summary>
        [Fact]
        public void DesignedThicknessTest()
        {
            // TODO unit test for the property 'DesignedThickness'
        }

        /// <summary>
        /// Test the property 'NormalStress'
        /// </summary>
        [Fact]
        public void NormalStressTest()
        {
            // TODO unit test for the property 'NormalStress'
        }

        /// <summary>
        /// Test the property 'ShearStress'
        /// </summary>
        [Fact]
        public void ShearStressTest()
        {
            // TODO unit test for the property 'ShearStress'
        }

        /// <summary>
        /// Test the property 'NormalStress2'
        /// </summary>
        [Fact]
        public void NormalStress2Test()
        {
            // TODO unit test for the property 'NormalStress2'
        }

        /// <summary>
        /// Test the property 'ShearStress2'
        /// </summary>
        [Fact]
        public void ShearStress2Test()
        {
            // TODO unit test for the property 'ShearStress2'
        }

        /// <summary>
        /// Test the property 'PlateName'
        /// </summary>
        [Fact]
        public void PlateNameTest()
        {
            // TODO unit test for the property 'PlateName'
        }

        /// <summary>
        /// Test the property 'Length'
        /// </summary>
        [Fact]
        public void LengthTest()
        {
            // TODO unit test for the property 'Length'
        }

        /// <summary>
        /// Test the property 'OriginId'
        /// </summary>
        [Fact]
        public void OriginIdTest()
        {
            // TODO unit test for the property 'OriginId'
        }

        /// <summary>
        /// Test the property 'SectionLine'
        /// </summary>
        [Fact]
        public void SectionLineTest()
        {
            // TODO unit test for the property 'SectionLine'
        }

        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }

        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }

        /// <summary>
        /// Test the property 'CheckStatus'
        /// </summary>
        [Fact]
        public void CheckStatusTest()
        {
            // TODO unit test for the property 'CheckStatus'
        }

        /// <summary>
        /// Test the property 'LimitCheckStatus'
        /// </summary>
        [Fact]
        public void LimitCheckStatusTest()
        {
            // TODO unit test for the property 'LimitCheckStatus'
        }

        /// <summary>
        /// Test the property 'LoadCaseId'
        /// </summary>
        [Fact]
        public void LoadCaseIdTest()
        {
            // TODO unit test for the property 'LoadCaseId'
        }

        /// <summary>
        /// Test the property 'LoadCase'
        /// </summary>
        [Fact]
        public void LoadCaseTest()
        {
            // TODO unit test for the property 'LoadCase'
        }

        /// <summary>
        /// Test the property 'MaxUnityCheck'
        /// </summary>
        [Fact]
        public void MaxUnityCheckTest()
        {
            // TODO unit test for the property 'MaxUnityCheck'
        }

        /// <summary>
        /// Test the property 'Form'
        /// </summary>
        [Fact]
        public void FormTest()
        {
            // TODO unit test for the property 'Form'
        }
    }
}
