/*
 * Connection Rest API 1.0
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using connection_restapi_client_poc.Model;
using connection_restapi_client_poc.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace connection_restapi_client_poc.Test.Model
{
    /// <summary>
    ///  Class for testing IdeaStatiCaApiConnectionModelConCalculationParameterIdeaStatiCaApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class IdeaStatiCaApiConnectionModelConCalculationParameterIdeaStatiCaApiTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for IdeaStatiCaApiConnectionModelConCalculationParameterIdeaStatiCaApi
        //private IdeaStatiCaApiConnectionModelConCalculationParameterIdeaStatiCaApi instance;

        public IdeaStatiCaApiConnectionModelConCalculationParameterIdeaStatiCaApiTests()
        {
            // TODO uncomment below to create an instance of IdeaStatiCaApiConnectionModelConCalculationParameterIdeaStatiCaApi
            //instance = new IdeaStatiCaApiConnectionModelConCalculationParameterIdeaStatiCaApi();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of IdeaStatiCaApiConnectionModelConCalculationParameterIdeaStatiCaApi
        /// </summary>
        [Fact]
        public void IdeaStatiCaApiConnectionModelConCalculationParameterIdeaStatiCaApiInstanceTest()
        {
            // TODO uncomment below to test "IsType" IdeaStatiCaApiConnectionModelConCalculationParameterIdeaStatiCaApi
            //Assert.IsType<IdeaStatiCaApiConnectionModelConCalculationParameterIdeaStatiCaApi>(instance);
        }

        /// <summary>
        /// Test the property 'ConnectionIds'
        /// </summary>
        [Fact]
        public void ConnectionIdsTest()
        {
            // TODO unit test for the property 'ConnectionIds'
        }

        /// <summary>
        /// Test the property 'AnalysisType'
        /// </summary>
        [Fact]
        public void AnalysisTypeTest()
        {
            // TODO unit test for the property 'AnalysisType'
        }
    }
}
