/*
 * Connection Rest API 1.0
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using connection_restapi_client_poc.Model;
using connection_restapi_client_poc.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace connection_restapi_client_poc.Test.Model
{
    /// <summary>
    ///  Class for testing IdeaStatiCaApiConnectionModelConLoadEffectIdeaStatiCaApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class IdeaStatiCaApiConnectionModelConLoadEffectIdeaStatiCaApiTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for IdeaStatiCaApiConnectionModelConLoadEffectIdeaStatiCaApi
        //private IdeaStatiCaApiConnectionModelConLoadEffectIdeaStatiCaApi instance;

        public IdeaStatiCaApiConnectionModelConLoadEffectIdeaStatiCaApiTests()
        {
            // TODO uncomment below to create an instance of IdeaStatiCaApiConnectionModelConLoadEffectIdeaStatiCaApi
            //instance = new IdeaStatiCaApiConnectionModelConLoadEffectIdeaStatiCaApi();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of IdeaStatiCaApiConnectionModelConLoadEffectIdeaStatiCaApi
        /// </summary>
        [Fact]
        public void IdeaStatiCaApiConnectionModelConLoadEffectIdeaStatiCaApiInstanceTest()
        {
            // TODO uncomment below to test "IsType" IdeaStatiCaApiConnectionModelConLoadEffectIdeaStatiCaApi
            //Assert.IsType<IdeaStatiCaApiConnectionModelConLoadEffectIdeaStatiCaApi>(instance);
        }

        /// <summary>
        /// Test the property 'IsPercentage'
        /// </summary>
        [Fact]
        public void IsPercentageTest()
        {
            // TODO unit test for the property 'IsPercentage'
        }

        /// <summary>
        /// Test the property 'MemberLoadings'
        /// </summary>
        [Fact]
        public void MemberLoadingsTest()
        {
            // TODO unit test for the property 'MemberLoadings'
        }

        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }

        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }

        /// <summary>
        /// Test the property 'Active'
        /// </summary>
        [Fact]
        public void ActiveTest()
        {
            // TODO unit test for the property 'Active'
        }
    }
}
