/*
 * Connection Rest API 1.0
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using connection_restapi_client_poc.Model;
using connection_restapi_client_poc.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace connection_restapi_client_poc.Test.Model
{
    /// <summary>
    ///  Class for testing MessageOpenMessagesIdeaRSOpenModel
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class MessageOpenMessagesIdeaRSOpenModelTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for MessageOpenMessagesIdeaRSOpenModel
        //private MessageOpenMessagesIdeaRSOpenModel instance;

        public MessageOpenMessagesIdeaRSOpenModelTests()
        {
            // TODO uncomment below to create an instance of MessageOpenMessagesIdeaRSOpenModel
            //instance = new MessageOpenMessagesIdeaRSOpenModel();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of MessageOpenMessagesIdeaRSOpenModel
        /// </summary>
        [Fact]
        public void MessageOpenMessagesIdeaRSOpenModelInstanceTest()
        {
            // TODO uncomment below to test "IsType" MessageOpenMessagesIdeaRSOpenModel
            //Assert.IsType<MessageOpenMessagesIdeaRSOpenModel>(instance);
        }

        /// <summary>
        /// Test the property 'Messages'
        /// </summary>
        [Fact]
        public void MessagesTest()
        {
            // TODO unit test for the property 'Messages'
        }
    }
}
