/*
 * Connection Rest API 1.0
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using connection_restapi_client_poc.Model;
using connection_restapi_client_poc.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace connection_restapi_client_poc.Test.Model
{
    /// <summary>
    ///  Class for testing ModelElement1DIdeaRSOpenModel
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ModelElement1DIdeaRSOpenModelTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ModelElement1DIdeaRSOpenModel
        //private ModelElement1DIdeaRSOpenModel instance;

        public ModelElement1DIdeaRSOpenModelTests()
        {
            // TODO uncomment below to create an instance of ModelElement1DIdeaRSOpenModel
            //instance = new ModelElement1DIdeaRSOpenModel();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ModelElement1DIdeaRSOpenModel
        /// </summary>
        [Fact]
        public void ModelElement1DIdeaRSOpenModelInstanceTest()
        {
            // TODO uncomment below to test "IsType" ModelElement1DIdeaRSOpenModel
            //Assert.IsType<ModelElement1DIdeaRSOpenModel>(instance);
        }

        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
    }
}
