/*
 * Connection Rest API 1.0
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using connection_restapi_client_poc.Model;
using connection_restapi_client_poc.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace connection_restapi_client_poc.Test.Model
{
    /// <summary>
    ///  Class for testing OkObjectResult
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class OkObjectResultTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for OkObjectResult
        //private OkObjectResult instance;

        public OkObjectResultTests()
        {
            // TODO uncomment below to create an instance of OkObjectResult
            //instance = new OkObjectResult();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of OkObjectResult
        /// </summary>
        [Fact]
        public void OkObjectResultInstanceTest()
        {
            // TODO uncomment below to test "IsType" OkObjectResult
            //Assert.IsType<OkObjectResult>(instance);
        }

        /// <summary>
        /// Test the property 'Value'
        /// </summary>
        [Fact]
        public void ValueTest()
        {
            // TODO unit test for the property 'Value'
        }

        /// <summary>
        /// Test the property 'Formatters'
        /// </summary>
        [Fact]
        public void FormattersTest()
        {
            // TODO unit test for the property 'Formatters'
        }

        /// <summary>
        /// Test the property 'ContentTypes'
        /// </summary>
        [Fact]
        public void ContentTypesTest()
        {
            // TODO unit test for the property 'ContentTypes'
        }

        /// <summary>
        /// Test the property 'DeclaredType'
        /// </summary>
        [Fact]
        public void DeclaredTypeTest()
        {
            // TODO unit test for the property 'DeclaredType'
        }

        /// <summary>
        /// Test the property 'StatusCode'
        /// </summary>
        [Fact]
        public void StatusCodeTest()
        {
            // TODO unit test for the property 'StatusCode'
        }
    }
}
