/**
 * Connection Rest API 1.0
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export enum ConAnalysisTypeEnum {
    StressStrain = <any> 'stress_Strain',
    Stiffness = <any> 'stiffness',
    CapacityDesign = <any> 'capacity_Design',
    Fatigues = <any> 'fatigues',
    TotalDesign = <any> 'total_Design',
    HorizontalTying = <any> 'horizontalTying',
    CapacityLoadLevels = <any> 'capacityLoadLevels',
    FireRestance = <any> 'fireRestance',
    Buckling = <any> 'buckling'
}
