/**
 * Connection Rest API 1.0
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { Line } from './line';
import { Selected } from './selected';
import { Text } from './text';

export class IGroup {
    'faces'?: Array<number> | null;
    'selected'?: Selected;
    'lines'?: Array<Line> | null;
    'priority'?: number;
    'text'?: Array<Text> | null;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "faces",
            "baseName": "faces",
            "type": "Array<number>"
        },
        {
            "name": "selected",
            "baseName": "selected",
            "type": "Selected"
        },
        {
            "name": "lines",
            "baseName": "lines",
            "type": "Array<Line>"
        },
        {
            "name": "priority",
            "baseName": "priority",
            "type": "number"
        },
        {
            "name": "text",
            "baseName": "text",
            "type": "Array<Text>"
        }    ];

    static getAttributeTypeMap() {
        return IGroup.attributeTypeMap;
    }
}

