/**
 * Connection Rest API 1.0
 * API for designing steel connections
 *
 * The version of the OpenAPI document: 1.0
 * Contact: info@ideastatica.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { OpenElementId } from './openElementId';

/**
* Reference element class
*/
export class ReferenceElement {
    /**
    * Element type name
    */
    'typeName'?: string | null;
    /**
    * Element Id
    */
    'id'?: number;
    'element'?: OpenElementId;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "typeName",
            "baseName": "typeName",
            "type": "string"
        },
        {
            "name": "id",
            "baseName": "id",
            "type": "number"
        },
        {
            "name": "element",
            "baseName": "element",
            "type": "OpenElementId"
        }    ];

    static getAttributeTypeMap() {
        return ReferenceElement.attributeTypeMap;
    }
}

