/**
 * Connection Rest API 1.0
 * API for designing steel connections
 *
 * The version of the OpenAPI document: 1.0
 * Contact: info@ideastatica.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { TextPosition } from './textPosition';

export class Text {
    'color'?: Array<number> | null;
    'value'?: string | null;
    'position'?: TextPosition;
    'fontSize'?: number;
    'tag'?: number;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "color",
            "baseName": "color",
            "type": "Array<number>"
        },
        {
            "name": "value",
            "baseName": "value",
            "type": "string"
        },
        {
            "name": "position",
            "baseName": "position",
            "type": "TextPosition"
        },
        {
            "name": "fontSize",
            "baseName": "fontSize",
            "type": "number"
        },
        {
            "name": "tag",
            "baseName": "tag",
            "type": "number"
        }    ];

    static getAttributeTypeMap() {
        return Text.attributeTypeMap;
    }
}

