/**
 * Connection Rest API 1.0
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class TextPosition {
    'origin'?: Array<number> | null;
    'angles'?: Array<number> | null;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "origin",
            "baseName": "origin",
            "type": "Array<number>"
        },
        {
            "name": "angles",
            "baseName": "angles",
            "type": "Array<number>"
        }    ];

    static getAttributeTypeMap() {
        return TextPosition.attributeTypeMap;
    }
}

