/**
 * Connection Rest API 1.0
 * IDEA StatiCa Connection API, used for the automated design and calculation of steel connections.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: info@ideastatica.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

/**
* WeldEvaluation
*/
export enum WeldEvaluation {
    MaxForceElement = <any> 'maxForceElement',
    ForceResultant = <any> 'forceResultant',
    ApplyPlasticWelds = <any> 'applyPlasticWelds'
}
