/*
 * Connection Rest API 1.0
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = connection_restapi_client_poc.Client.OpenAPIDateConverter;

namespace connection_restapi_client_poc.Model
{
    /// <summary>
    /// Defines Data_WeldingTypeSNIP-CI_BasicTypes
    /// </summary>
    [JsonConverter(typeof(StringEnumConverter))]
    public enum DataWeldingTypeSNIPCIBasicTypes
    {
        /// <summary>
        /// Enum Manual for value: manual
        /// </summary>
        [EnumMember(Value = "manual")]
        Manual = 1,

        /// <summary>
        /// Enum ManualSmallRodDiam for value: manualSmallRodDiam
        /// </summary>
        [EnumMember(Value = "manualSmallRodDiam")]
        ManualSmallRodDiam = 2,

        /// <summary>
        /// Enum AutomaticAndMachine for value: automaticAndMachine
        /// </summary>
        [EnumMember(Value = "automaticAndMachine")]
        AutomaticAndMachine = 3,

        /// <summary>
        /// Enum Automatic for value: automatic
        /// </summary>
        [EnumMember(Value = "automatic")]
        Automatic = 4
    }

}
