/*
 * Connection Rest API 1.0
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = connection_restapi_client_poc.Client.OpenAPIDateConverter;

namespace connection_restapi_client_poc.Model
{
    /// <summary>
    /// FireTemperatureCalculationDataIdeaRSConnectionCalculator
    /// </summary>
    [DataContract(Name = "FireTemperatureCalculationData-IdeaRS_ConnectionCalculator")]
    public partial class FireTemperatureCalculationDataIdeaRSConnectionCalculator : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="FireTemperatureCalculationDataIdeaRSConnectionCalculator" /> class.
        /// </summary>
        /// <param name="totalExposureTime">totalExposureTime.</param>
        /// <param name="timeInterval">timeInterval.</param>
        /// <param name="initTemperature">initTemperature.</param>
        /// <param name="fireTemperature">fireTemperature.</param>
        /// <param name="temperatureIncrease">temperatureIncrease.</param>
        public FireTemperatureCalculationDataIdeaRSConnectionCalculator(int totalExposureTime = default(int), int timeInterval = default(int), double initTemperature = default(double), double fireTemperature = default(double), double temperatureIncrease = default(double))
        {
            this.TotalExposureTime = totalExposureTime;
            this.TimeInterval = timeInterval;
            this.InitTemperature = initTemperature;
            this.FireTemperature = fireTemperature;
            this.TemperatureIncrease = temperatureIncrease;
        }

        /// <summary>
        /// Gets or Sets TotalExposureTime
        /// </summary>
        [DataMember(Name = "totalExposureTime", EmitDefaultValue = false)]
        public int TotalExposureTime { get; set; }

        /// <summary>
        /// Gets or Sets TimeInterval
        /// </summary>
        [DataMember(Name = "timeInterval", EmitDefaultValue = false)]
        public int TimeInterval { get; set; }

        /// <summary>
        /// Gets or Sets InitTemperature
        /// </summary>
        [DataMember(Name = "initTemperature", EmitDefaultValue = false)]
        public double InitTemperature { get; set; }

        /// <summary>
        /// Gets or Sets FireTemperature
        /// </summary>
        [DataMember(Name = "fireTemperature", EmitDefaultValue = false)]
        public double FireTemperature { get; set; }

        /// <summary>
        /// Gets or Sets TemperatureIncrease
        /// </summary>
        [DataMember(Name = "temperatureIncrease", EmitDefaultValue = false)]
        public double TemperatureIncrease { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class FireTemperatureCalculationDataIdeaRSConnectionCalculator {\n");
            sb.Append("  TotalExposureTime: ").Append(TotalExposureTime).Append("\n");
            sb.Append("  TimeInterval: ").Append(TimeInterval).Append("\n");
            sb.Append("  InitTemperature: ").Append(InitTemperature).Append("\n");
            sb.Append("  FireTemperature: ").Append(FireTemperature).Append("\n");
            sb.Append("  TemperatureIncrease: ").Append(TemperatureIncrease).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
