/*
 * Connection Rest API 1.0
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = connection_restapi_client_poc.Client.OpenAPIDateConverter;

namespace connection_restapi_client_poc.Model
{
    /// <summary>
    /// IdeaStatiCaApiConnectionModelProjMaterialIdeaStatiCaApi
    /// </summary>
    [DataContract(Name = "IdeaStatiCa_Api_Connection_Model_ProjMaterial-IdeaStatiCa_Api")]
    public partial class IdeaStatiCaApiConnectionModelProjMaterialIdeaStatiCaApi : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="IdeaStatiCaApiConnectionModelProjMaterialIdeaStatiCaApi" /> class.
        /// </summary>
        /// <param name="materialType">materialType.</param>
        /// <param name="isFromMrplDatabase">isFromMrplDatabase.</param>
        /// <param name="canEdit">canEdit.</param>
        /// <param name="id">id.</param>
        /// <param name="name">name.</param>
        public IdeaStatiCaApiConnectionModelProjMaterialIdeaStatiCaApi(string materialType = default(string), string isFromMrplDatabase = default(string), bool canEdit = default(bool), int id = default(int), string name = default(string))
        {
            this.MaterialType = materialType;
            this.IsFromMrplDatabase = isFromMrplDatabase;
            this.CanEdit = canEdit;
            this.Id = id;
            this.Name = name;
        }

        /// <summary>
        /// Gets or Sets MaterialType
        /// </summary>
        [DataMember(Name = "materialType", EmitDefaultValue = true)]
        public string MaterialType { get; set; }

        /// <summary>
        /// Gets or Sets IsFromMrplDatabase
        /// </summary>
        [DataMember(Name = "isFromMrplDatabase", EmitDefaultValue = true)]
        public string IsFromMrplDatabase { get; set; }

        /// <summary>
        /// Gets or Sets CanEdit
        /// </summary>
        [DataMember(Name = "canEdit", EmitDefaultValue = true)]
        public bool CanEdit { get; set; }

        /// <summary>
        /// Gets or Sets Id
        /// </summary>
        [DataMember(Name = "id", EmitDefaultValue = false)]
        public int Id { get; set; }

        /// <summary>
        /// Gets or Sets Name
        /// </summary>
        [DataMember(Name = "name", EmitDefaultValue = true)]
        public string Name { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class IdeaStatiCaApiConnectionModelProjMaterialIdeaStatiCaApi {\n");
            sb.Append("  MaterialType: ").Append(MaterialType).Append("\n");
            sb.Append("  IsFromMrplDatabase: ").Append(IsFromMrplDatabase).Append("\n");
            sb.Append("  CanEdit: ").Append(CanEdit).Append("\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("  Name: ").Append(Name).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
