/*
 * Connection Rest API 1.0
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = connection_restapi_client_poc.Client.OpenAPIDateConverter;

namespace connection_restapi_client_poc.Model
{
    /// <summary>
    /// IdeaStatiCaApiConnectionModelConProjectIdeaStatiCaApi
    /// </summary>
    [DataContract(Name = "IdeaStatiCa_Api_Connection_Model_ConProject-IdeaStatiCa_Api")]
    public partial class IdeaStatiCaApiConnectionModelConProjectIdeaStatiCaApi : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="IdeaStatiCaApiConnectionModelConProjectIdeaStatiCaApi" /> class.
        /// </summary>
        /// <param name="projectId">projectId.</param>
        /// <param name="projectInfo">projectInfo.</param>
        /// <param name="connections">connections.</param>
        public IdeaStatiCaApiConnectionModelConProjectIdeaStatiCaApi(Guid projectId = default(Guid), IdeaStatiCaApiConnectionModelConProjectDataIdeaStatiCaApi projectInfo = default(IdeaStatiCaApiConnectionModelConProjectDataIdeaStatiCaApi), List<IdeaStatiCaApiConnectionModelConConnectionIdeaStatiCaApi> connections = default(List<IdeaStatiCaApiConnectionModelConConnectionIdeaStatiCaApi>))
        {
            this.ProjectId = projectId;
            this.ProjectInfo = projectInfo;
            this.Connections = connections;
        }

        /// <summary>
        /// Gets or Sets ProjectId
        /// </summary>
        [DataMember(Name = "projectId", EmitDefaultValue = false)]
        public Guid ProjectId { get; set; }

        /// <summary>
        /// Gets or Sets ProjectInfo
        /// </summary>
        [DataMember(Name = "projectInfo", EmitDefaultValue = false)]
        public IdeaStatiCaApiConnectionModelConProjectDataIdeaStatiCaApi ProjectInfo { get; set; }

        /// <summary>
        /// Gets or Sets Connections
        /// </summary>
        [DataMember(Name = "connections", EmitDefaultValue = true)]
        public List<IdeaStatiCaApiConnectionModelConConnectionIdeaStatiCaApi> Connections { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class IdeaStatiCaApiConnectionModelConProjectIdeaStatiCaApi {\n");
            sb.Append("  ProjectId: ").Append(ProjectId).Append("\n");
            sb.Append("  ProjectInfo: ").Append(ProjectInfo).Append("\n");
            sb.Append("  Connections: ").Append(Connections).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
