/*
 * Connection Rest API 1.0
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = connection_restapi_client_poc.Client.OpenAPIDateConverter;

namespace connection_restapi_client_poc.Model
{
    /// <summary>
    /// PlateCheckLocalDeformationIdeaStatiCaConnectionChecks
    /// </summary>
    [DataContract(Name = "PlateCheckLocalDeformation-IdeaStatiCa_ConnectionChecks")]
    public partial class PlateCheckLocalDeformationIdeaStatiCaConnectionChecks : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="PlateCheckLocalDeformationIdeaStatiCaConnectionChecks" /> class.
        /// </summary>
        /// <param name="maxDeformation">maxDeformation.</param>
        /// <param name="maxDeformationRatio">maxDeformationRatio.</param>
        /// <param name="limitDeformation">limitDeformation.</param>
        /// <param name="thickness">thickness.</param>
        /// <param name="csize">csize.</param>
        /// <param name="materialName">materialName.</param>
        /// <param name="items">items.</param>
        /// <param name="id">id.</param>
        /// <param name="name">name.</param>
        /// <param name="checkStatus">checkStatus.</param>
        /// <param name="limitCheckStatus">limitCheckStatus.</param>
        /// <param name="loadCaseId">loadCaseId.</param>
        /// <param name="loadCase">loadCase.</param>
        /// <param name="maxUnityCheck">maxUnityCheck.</param>
        /// <param name="form">form.</param>
        public PlateCheckLocalDeformationIdeaStatiCaConnectionChecks(double maxDeformation = default(double), double maxDeformationRatio = default(double), double limitDeformation = default(double), double thickness = default(double), double csize = default(double), string materialName = default(string), List<int> items = default(List<int>), int id = default(int), string name = default(string), bool checkStatus = default(bool), bool limitCheckStatus = default(bool), int loadCaseId = default(int), string loadCase = default(string), double maxUnityCheck = default(double), string form = default(string))
        {
            this.MaxDeformation = maxDeformation;
            this.MaxDeformationRatio = maxDeformationRatio;
            this.LimitDeformation = limitDeformation;
            this.Thickness = thickness;
            this.Csize = csize;
            this.MaterialName = materialName;
            this.Items = items;
            this.Id = id;
            this.Name = name;
            this.CheckStatus = checkStatus;
            this.LimitCheckStatus = limitCheckStatus;
            this.LoadCaseId = loadCaseId;
            this.LoadCase = loadCase;
            this.MaxUnityCheck = maxUnityCheck;
            this.Form = form;
        }

        /// <summary>
        /// Gets or Sets MaxDeformation
        /// </summary>
        [DataMember(Name = "maxDeformation", EmitDefaultValue = false)]
        public double MaxDeformation { get; set; }

        /// <summary>
        /// Gets or Sets MaxDeformationRatio
        /// </summary>
        [DataMember(Name = "maxDeformationRatio", EmitDefaultValue = false)]
        public double MaxDeformationRatio { get; set; }

        /// <summary>
        /// Gets or Sets LimitDeformation
        /// </summary>
        [DataMember(Name = "limitDeformation", EmitDefaultValue = false)]
        public double LimitDeformation { get; set; }

        /// <summary>
        /// Gets or Sets Thickness
        /// </summary>
        [DataMember(Name = "thickness", EmitDefaultValue = false)]
        public double Thickness { get; set; }

        /// <summary>
        /// Gets or Sets Csize
        /// </summary>
        [DataMember(Name = "csize", EmitDefaultValue = false)]
        public double Csize { get; set; }

        /// <summary>
        /// Gets or Sets MaterialName
        /// </summary>
        [DataMember(Name = "materialName", EmitDefaultValue = true)]
        public string MaterialName { get; set; }

        /// <summary>
        /// Gets or Sets Items
        /// </summary>
        [DataMember(Name = "items", EmitDefaultValue = true)]
        public List<int> Items { get; set; }

        /// <summary>
        /// Gets or Sets Id
        /// </summary>
        [DataMember(Name = "id", EmitDefaultValue = false)]
        public int Id { get; set; }

        /// <summary>
        /// Gets or Sets Name
        /// </summary>
        [DataMember(Name = "name", EmitDefaultValue = true)]
        public string Name { get; set; }

        /// <summary>
        /// Gets or Sets CheckStatus
        /// </summary>
        [DataMember(Name = "checkStatus", EmitDefaultValue = true)]
        public bool CheckStatus { get; set; }

        /// <summary>
        /// Gets or Sets LimitCheckStatus
        /// </summary>
        [DataMember(Name = "limitCheckStatus", EmitDefaultValue = true)]
        public bool LimitCheckStatus { get; set; }

        /// <summary>
        /// Gets or Sets LoadCaseId
        /// </summary>
        [DataMember(Name = "loadCaseId", EmitDefaultValue = false)]
        public int LoadCaseId { get; set; }

        /// <summary>
        /// Gets or Sets LoadCase
        /// </summary>
        [DataMember(Name = "loadCase", EmitDefaultValue = true)]
        public string LoadCase { get; set; }

        /// <summary>
        /// Gets or Sets MaxUnityCheck
        /// </summary>
        [DataMember(Name = "maxUnityCheck", EmitDefaultValue = false)]
        public double MaxUnityCheck { get; set; }

        /// <summary>
        /// Gets or Sets Form
        /// </summary>
        [DataMember(Name = "form", EmitDefaultValue = true)]
        public string Form { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class PlateCheckLocalDeformationIdeaStatiCaConnectionChecks {\n");
            sb.Append("  MaxDeformation: ").Append(MaxDeformation).Append("\n");
            sb.Append("  MaxDeformationRatio: ").Append(MaxDeformationRatio).Append("\n");
            sb.Append("  LimitDeformation: ").Append(LimitDeformation).Append("\n");
            sb.Append("  Thickness: ").Append(Thickness).Append("\n");
            sb.Append("  Csize: ").Append(Csize).Append("\n");
            sb.Append("  MaterialName: ").Append(MaterialName).Append("\n");
            sb.Append("  Items: ").Append(Items).Append("\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("  Name: ").Append(Name).Append("\n");
            sb.Append("  CheckStatus: ").Append(CheckStatus).Append("\n");
            sb.Append("  LimitCheckStatus: ").Append(LimitCheckStatus).Append("\n");
            sb.Append("  LoadCaseId: ").Append(LoadCaseId).Append("\n");
            sb.Append("  LoadCase: ").Append(LoadCase).Append("\n");
            sb.Append("  MaxUnityCheck: ").Append(MaxUnityCheck).Append("\n");
            sb.Append("  Form: ").Append(Form).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
