# coding: utf-8

"""
    ConDesignProposer API 9.0

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 9.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from idea_cdp_client_poc.models.con_design_set_dto import ConDesignSetDto

class TestConDesignSetDto(unittest.TestCase):
    """ConDesignSetDto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ConDesignSetDto:
        """Test ConDesignSetDto
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ConDesignSetDto`
        """
        model = ConDesignSetDto()
        if include_optional:
            return ConDesignSetDto(
                id = '',
                name = '',
                description = '',
                read_only = True,
                owner_id = '',
                created = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                modified = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                type = 0,
                permissions = [
                    0
                    ]
            )
        else:
            return ConDesignSetDto(
        )
        """

    def testConDesignSetDto(self):
        """Test ConDesignSetDto"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
