# coding: utf-8

"""
    ConDesignProposer API 9.0

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 9.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from idea_cdp_client_poc.api.design_item_api import DesignItemApi


class TestDesignItemApi(unittest.TestCase):
    """DesignItemApi unit test stubs"""

    def setUp(self) -> None:
        self.api = DesignItemApi()

    def tearDown(self) -> None:
        pass

    def test_api9_design_items_design_item_id_delete(self) -> None:
        """Test case for api9_design_items_design_item_id_delete

        """
        pass

    def test_api9_design_items_design_item_id_get(self) -> None:
        """Test case for api9_design_items_design_item_id_get

        """
        pass

    def test_api9_design_items_design_item_id_picture_get(self) -> None:
        """Test case for api9_design_items_design_item_id_picture_get

        """
        pass

    def test_api9_design_items_design_item_id_picture_url_get(self) -> None:
        """Test case for api9_design_items_design_item_id_picture_url_get

        """
        pass

    def test_api9_design_items_design_item_id_template_get(self) -> None:
        """Test case for api9_design_items_design_item_id_template_get

        """
        pass

    def test_api9_design_items_design_item_id_training_post(self) -> None:
        """Test case for api9_design_items_design_item_id_training_post

        """
        pass

    def test_api9_design_items_post(self) -> None:
        """Test case for api9_design_items_post

        """
        pass

    def test_api9_design_items_put(self) -> None:
        """Test case for api9_design_items_put

        """
        pass

    def test_api9_design_items_without_scene_post(self) -> None:
        """Test case for api9_design_items_without_scene_post

        """
        pass


if __name__ == '__main__':
    unittest.main()
