# coding: utf-8

"""
    ConDesignProposer API 9.0

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 9.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from idea_cdp_client_poc.api.design_project_api import DesignProjectApi


class TestDesignProjectApi(unittest.TestCase):
    """DesignProjectApi unit test stubs"""

    def setUp(self) -> None:
        self.api = DesignProjectApi()

    def tearDown(self) -> None:
        pass

    def test_api9_design_project_design_item_id_get(self) -> None:
        """Test case for api9_design_project_design_item_id_get

        """
        pass

    def test_api9_design_project_get(self) -> None:
        """Test case for api9_design_project_get

        """
        pass


if __name__ == '__main__':
    unittest.main()
