# coding: utf-8

"""
    Connection Rest API 1.0

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from connection_restapi_client_poc.models.anchor_grid import AnchorGrid

class TestAnchorGrid(unittest.TestCase):
    """AnchorGrid unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AnchorGrid:
        """Test AnchorGrid
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AnchorGrid`
        """
        model = AnchorGrid()
        if include_optional:
            return AnchorGrid(
                concrete_block = connection_restapi_client_poc.models.concrete_block.ConcreteBlock(
                    lenght = 1.337, 
                    width = 1.337, 
                    height = 1.337, 
                    material = '', ),
                anchor_type = 'straight',
                washer_size = 1.337,
                bolt_assembly_ref = '',
                id = 56,
                is_anchor = True,
                anchor_len = 1.337,
                hole_diameter = 1.337,
                diameter = 1.337,
                head_diameter = 1.337,
                diagonal_head_diameter = 1.337,
                head_height = 1.337,
                bore_hole = 1.337,
                tensile_stress_area = 1.337,
                nut_thickness = 1.337,
                bolt_assembly_name = '',
                standard = '',
                material = '',
                origin = connection_restapi_client_poc.models.point3_d.Point3D(
                    x = 1.337, 
                    y = 1.337, 
                    z = 1.337, 
                    id = 56, ),
                axis_x = connection_restapi_client_poc.models.vector3_d.Vector3D(
                    x = 1.337, 
                    y = 1.337, 
                    z = 1.337, ),
                axis_y = connection_restapi_client_poc.models.vector3_d.Vector3D(
                    x = 1.337, 
                    y = 1.337, 
                    z = 1.337, ),
                axis_z = connection_restapi_client_poc.models.vector3_d.Vector3D(
                    x = 1.337, 
                    y = 1.337, 
                    z = 1.337, ),
                positions = [
                    connection_restapi_client_poc.models.point3_d.Point3D(
                        x = 1.337, 
                        y = 1.337, 
                        z = 1.337, 
                        id = 56, )
                    ],
                connected_plates = [
                    56
                    ],
                connected_part_ids = [
                    ''
                    ],
                shear_in_thread = True,
                bolt_interaction = 'bearing'
            )
        else:
            return AnchorGrid(
        )
        """

    def testAnchorGrid(self):
        """Test AnchorGrid"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
