# coding: utf-8

"""
    Connection Rest API 1.0

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from connection_restapi_client_poc.models.con_template_apply_param import ConTemplateApplyParam

class TestConTemplateApplyParam(unittest.TestCase):
    """ConTemplateApplyParam unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ConTemplateApplyParam:
        """Test ConTemplateApplyParam
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ConTemplateApplyParam`
        """
        model = ConTemplateApplyParam()
        if include_optional:
            return ConTemplateApplyParam(
                connection_template = '',
                mapping = connection_restapi_client_poc.models.template_conversions.TemplateConversions(
                    conversions = [
                        connection_restapi_client_poc.models.base_template_conversion.BaseTemplateConversion(
                            original_value = '', 
                            original_template_id = '', 
                            new_value = '', 
                            description = '', 
                            new_template_id = '', )
                        ], 
                    country_code = '', )
            )
        else:
            return ConTemplateApplyParam(
        )
        """

    def testConTemplateApplyParam(self):
        """Test ConTemplateApplyParam"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
