/*
 * Connection Rest API 1.0
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using Xunit;

using connection_restapi_client_poc.Client;
using connection_restapi_client_poc.Api;
// uncomment below to import models
//using connection_restapi_client_poc.Model;

namespace connection_restapi_client_poc.Test.Api
{
    /// <summary>
    ///  Class for testing ExportApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    public class ExportApiTests : IDisposable
    {
        private ExportApi instance;

        public ExportApiTests()
        {
            instance = new ExportApi();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ExportApi
        /// </summary>
        [Fact]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsType' ExportApi
            //Assert.IsType<ExportApi>(instance);
        }

        /// <summary>
        /// Test Api1ProjectsProjectIdConnectionsConnectionIdExportIfcGet
        /// </summary>
        [Fact]
        public void Api1ProjectsProjectIdConnectionsConnectionIdExportIfcGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //Guid projectId = null;
            //int connectionId = null;
            //var response = instance.Api1ProjectsProjectIdConnectionsConnectionIdExportIfcGet(projectId, connectionId);
            //Assert.IsType<SystemIOMemoryStreamSystemPrivateCoreLib>(response);
        }

        /// <summary>
        /// Test Api1ProjectsProjectIdConnectionsConnectionIdExportIomConnectionDataGet
        /// </summary>
        [Fact]
        public void Api1ProjectsProjectIdConnectionsConnectionIdExportIomConnectionDataGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //Guid projectId = null;
            //int connectionId = null;
            //var response = instance.Api1ProjectsProjectIdConnectionsConnectionIdExportIomConnectionDataGet(projectId, connectionId);
            //Assert.IsType<ConnectionConnectionDataIdeaRSOpenModel>(response);
        }

        /// <summary>
        /// Test Api1ProjectsProjectIdConnectionsConnectionIdExportIomGet
        /// </summary>
        [Fact]
        public void Api1ProjectsProjectIdConnectionsConnectionIdExportIomGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //Guid projectId = null;
            //int connectionId = null;
            //string? version = null;
            //instance.Api1ProjectsProjectIdConnectionsConnectionIdExportIomGet(projectId, connectionId, version);
        }
    }
}
