/**
 * Connection Rest API 1.0
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class Stream {
    'canRead'?: boolean;
    'canWrite'?: boolean;
    'canSeek'?: boolean;
    'canTimeout'?: boolean;
    'length'?: number;
    'position'?: number;
    'readTimeout'?: number;
    'writeTimeout'?: number;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "canRead",
            "baseName": "canRead",
            "type": "boolean"
        },
        {
            "name": "canWrite",
            "baseName": "canWrite",
            "type": "boolean"
        },
        {
            "name": "canSeek",
            "baseName": "canSeek",
            "type": "boolean"
        },
        {
            "name": "canTimeout",
            "baseName": "canTimeout",
            "type": "boolean"
        },
        {
            "name": "length",
            "baseName": "length",
            "type": "number"
        },
        {
            "name": "position",
            "baseName": "position",
            "type": "number"
        },
        {
            "name": "readTimeout",
            "baseName": "readTimeout",
            "type": "number"
        },
        {
            "name": "writeTimeout",
            "baseName": "writeTimeout",
            "type": "number"
        }    ];

    static getAttributeTypeMap() {
        return Stream.attributeTypeMap;
    }
}

