/*
 * Connection Rest API 1.0
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = IdeaStatiCa.ConnectionApi.Client.OpenAPIDateConverter;

namespace IdeaStatiCa.ConnectionApi.Model
{
    /// <summary>
    /// Cross-section
    /// </summary>
    [DataContract(Name = "CrossSection")]
    public partial class CrossSection : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="CrossSection" /> class.
        /// </summary>
        /// <param name="name">Name of cross-section.</param>
        /// <param name="crossSectionRotation">Rotation of Cross - Section.</param>
        /// <param name="isInPrincipal">Specifies that the cross-section is in its principal axis..</param>
        /// <param name="id">Element Id.</param>
        public CrossSection(string name = default(string), double crossSectionRotation = default(double), bool isInPrincipal = default(bool), int id = default(int))
        {
            this.Name = name;
            this.CrossSectionRotation = crossSectionRotation;
            this.IsInPrincipal = isInPrincipal;
            this.Id = id;
        }

        /// <summary>
        /// Name of cross-section
        /// </summary>
        /// <value>Name of cross-section</value>
        [DataMember(Name = "name", EmitDefaultValue = true)]
        public string Name { get; set; }

        /// <summary>
        /// Rotation of Cross - Section
        /// </summary>
        /// <value>Rotation of Cross - Section</value>
        [DataMember(Name = "crossSectionRotation", EmitDefaultValue = false)]
        public double CrossSectionRotation { get; set; }

        /// <summary>
        /// Specifies that the cross-section is in its principal axis.
        /// </summary>
        /// <value>Specifies that the cross-section is in its principal axis.</value>
        [DataMember(Name = "isInPrincipal", EmitDefaultValue = true)]
        public bool IsInPrincipal { get; set; }

        /// <summary>
        /// Element Id
        /// </summary>
        /// <value>Element Id</value>
        [DataMember(Name = "id", EmitDefaultValue = false)]
        public int Id { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class CrossSection {\n");
            sb.Append("  Name: ").Append(Name).Append("\n");
            sb.Append("  CrossSectionRotation: ").Append(CrossSectionRotation).Append("\n");
            sb.Append("  IsInPrincipal: ").Append(IsInPrincipal).Append("\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
